# Generated by Django 6.0.4 on 2026-04-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OHLCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'ohlcv',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['symbol', 'timeframe', '-time'], name='idx_symbol_tf_time')],
                'unique_together': {('symbol', 'timeframe', 'time')},
            },
        ),
    ]
