# Generated by Django 6.0.4 on 2026-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField(help_text='MT5 order/position ticket', unique=True)),
                ('symbol', models.CharField(help_text='e.g. EURUSD, XAUUSD', max_length=20)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=6)),
                ('open_time', models.DateTimeField(help_text='When the position was opened')),
                ('close_time', models.DateTimeField(blank=True, help_text='Set when closed', null=True)),
                ('entry', models.DecimalField(decimal_places=5, help_text='Entry price', max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=5, help_text='Last known market price', max_digits=12)),
                ('sl', models.DecimalField(decimal_places=5, default=0, help_text='Stop Loss price', max_digits=12)),
                ('tp', models.DecimalField(decimal_places=5, default=0, help_text='Take Profit price', max_digits=12)),
                ('volume', models.DecimalField(decimal_places=2, help_text='Lot size, e.g. 0.10', max_digits=8)),
                ('profit', models.DecimalField(decimal_places=2, help_text='Floating or closed P&L in USD', max_digits=12)),
                ('magic', models.BigIntegerField(default=0, help_text='EA magic number')),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-open_time'],
                'indexes': [models.Index(fields=['symbol'], name='trades_trad_symbol_d6aee8_idx'), models.Index(fields=['status', '-open_time'], name='trades_trad_status_5b0e8e_idx')],
            },
        ),
    ]
